version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
  - misspell
  - govet
  - staticcheck
  - errcheck
  - ineffassign
  - unused
  - revive

formatters:
  enable:
  - goimports
  - gofmt
  - gofumpt
  - gci
  - golines

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
