services:
  api:
    image: golang:1.22
    platform: linux/arm64
    working_dir: /app
    volumes:
      - ./:/app
      - dbdata:/db
    environment:
      - HTTP_ADDRESS=0.0.0.0:8082
      - DB_DRIVER=sqlite
      - DB_PATH=/db/app.db
      - CORS_ALLOWED_ORIGINS=http://web:5173,http://localhost:5173,http://instance-agent.subnet05071228.vcn05071228.oraclevcn.com:5173
      - ENV=dev
      - GOTOOLCHAIN=go1.22.6
    command: sh -c "go mod download && go run ./cmd/server"
    depends_on:
      db:
        condition: service_started
    expose:
      - "8082"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8082/healthz >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  db:
    image: arm64v8/alpine:3.19
    platform: linux/arm64
    command: sh -c "apk add --no-cache sqlite sqlite-libs >/dev/null 2>&1 && sqlite3 /data/app.db 'PRAGMA user_version;' || true; tail -f /dev/null"
    volumes:
      - dbdata:/data
    healthcheck:
      test: ["CMD-SHELL", "sqlite3 /data/app.db 'PRAGMA user_version;' >/dev/null 2>&1 || sqlite3 /data/app.db '.databases' >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    image: node:18-alpine
    platform: linux/arm64
    working_dir: /app/web
    volumes:
      - ./web:/app/web
      - /app/web/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PROXY_TARGET=http://api:8082
    # Use npm ci for deterministic installs from package-lock.json
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy

  sqlite-admin:
    image: python:3.12-alpine
    platform: linux/arm64
    working_dir: /app
    volumes:
      - dbdata:/data
    command: sh -c "pip install --no-cache-dir sqlite-web && sqlite_web --host 0.0.0.0 --port 8080 /data/app.db"
    depends_on:
      db:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  dbdata:
