# syntax=docker/dockerfile:1.7
FROM python:3.11-alpine
WORKDIR /app
RUN apk add --no-cache ca-certificates && \
    pip install --no-cache-dir sqlite-web
CMD ["sqlite_web", "--host", "0.0.0.0", "--port", "8080", "/db/app.db"]
